### ISSUE TITLE
Any reasons why are you using a third party and not URLSession?

### ISSUE THREAD

**Issue by codecat15** [nvdmcs/MyExperiments#1]
https://github.com/nvdmcs/MyExperiments/blob/c9bc53ad822108d63a1281df5b5cd52aeffb4361/AalmofireJsonExample/AalmofireJsonExample/UserAPIManager.swift#L16

**Comment by naveedmcs** [comment]
this is because  in a large size project we hit multiple  network Api's in a different  way . threads auto manage by alamofire and also they provide some extra features for APi's request handling. it is also save our time.

**Comment by codecat15** [comment]
@nvdmcs  You can use `URLSession` to do literally all types of requests like `get`, `post`, `put` and `delete` what is the real purpose of using this library here? What is the issue that you are trying to solve that `URLSession` cannot solve? Speaking of extra features what are the extra features you are using with this library in your project that the default iOS framework cannot provide?

I would avoid using a third party library in the code at any cost and make sure I have default framework in place coz when the iOS updates those are the components which have less impact. However a third party library can cause more damage if something fails. Coming back to my comments please provide detailed summary of what are you trying to achieve with `alamofire`

**Comment by naveedmcs** [comment]
It’s a layer on top of URLSession with the goal to make common networking features easier to implement.

1- Certificate pinning. It can take some time to sort this out and build this yourself.
2-Requests retrying. When a request fails for example because of an authentication failure, you can easily refresh your authentication token and invoke the same request again without touching the implementation code.
3- Apart from these features, the syntax for building up requests is a lot more elegant and easier to use. It saves you from a lot extra code and makes validation and error handling a lot easier.
4- Network  reachability
AF Example 

`AF.request("https://api.mywebserver.com/v1/board", method: .get, parameters: ["title": "New York Highlights"])
    .validate(statusCode: 200..<300)
    .responseDecodable { (response: DataResponse) in
        switch response.result {
        case .success(let board):
            print("Created board title is \(board.title)") // New York Highlights
        case .failure(let error):
            print("Board creation failed with error: \(error.localizedDescription)")
        }
}`


Doing exactly the same with the URLSession API requires a bit more of work.


`enum Error: Swift.Error {
    case requestFailed
}

// Build up the URL
var components = URLComponents(string: "https://api.mywebserver.com/v1/board")!
components.queryItems = ["title": "New York Highlights"].map { (key, value) in
    URLQueryItem(name: key, value: value)
}

// Generate and execute the request
let request = try! URLRequest(url: components.url!, method: .get)
URLSession.shared.dataTask(with: request) { (data, response, error) in
    do {
        guard let data = data,
            let response = response as? HTTPURLResponse, (200 ..< 300) ~= response.statusCode,
            error == nil else {
            // Data was nil, validation failed or an error occurred.
            throw error ?? Error.requestFailed
        }
        let board = try JSONDecoder().decode(Board.self, from: data)
        print("Created board title is \(board.title)") // New York Highlights
    } catch {
        print("Board creation failed with error: \(error.localizedDescription)")
    }
}`

**Comment by naveedmcs** [comment]
Alamofire Thirday Party hony ki wja se iski maintainans support kbhi bhi khtm ho skti he :p 
R company ko third party se concern nae hota .. unka bs chly to kehty 10 din me project  khtm ho jana chhaye :p

**Comment by codecat15** [comment]
@nvdmcs I think you did not understand my question, let me ask it again out of the advantages you mentioned of `alamofire` how many are you using it in your project? If none then remove the library and use default framework.

If the best reasoning you can give me is the syntax of alamofire is awesome and URLSessions needs two more lines for a feature then I would ask you to get rid of alamofire from the project because to me those are fragile reason and if you want to detect the internet then use reachability class which does a good job of detecting the network.

If you have any strong reasons apart from that to use `alamofire` then yes you should use it, but whatever you said it seems the only reason you are using this library is to make api calls which to me is not a strong reason.

Alamofire has no connection with maintenance it's your code. The way we write our code is directly proportional to the cost of project maintenance, if the code is messy then unfortunately small feature implementation will take lots of time, but if it's clean it will be much easy to implement or update a feature.

**Comment by naveedmcs** [comment]
ok me apko bt se agree krta hu ... ok my future  practices is going to be URL Session
